<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Empleado;

class EmpleadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $empleados = [
            [
                'codigo_empleado' => 'EMP001',
                'nombres' => 'Juan Carlos',
                'apellidos' => 'García López',
                'dpi' => '1234567890101',
                'nit' => '12345678',
                'fecha_nacimiento' => '1985-03-15',
                'genero' => 'M',
                'estado_civil' => 'casado',
                'telefono' => '12345678',
                'email' => 'juan.garcia@sansare.gob.gt',
                'direccion' => 'Zona 1, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Director de Recursos Humanos',
                'area_trabajo' => 'Recursos Humanos',
                'salario_base' => 8500.00,
                'fecha_ingreso' => '2020-01-15',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678901',
                'numero_irtra' => '1234567',
                'contacto_emergencia_nombre' => 'María García',
                'contacto_emergencia_telefono' => '87654321',
                'contacto_emergencia_relacion' => 'esposa'
            ],
            [
                'codigo_empleado' => 'EMP002',
                'nombres' => 'María Elena',
                'apellidos' => 'Rodríguez Morales',
                'dpi' => '1234567890102',
                'nit' => '12345679',
                'fecha_nacimiento' => '1990-07-22',
                'genero' => 'F',
                'estado_civil' => 'soltero',
                'telefono' => '87654321',
                'email' => 'maria.rodriguez@sansare.gob.gt',
                'direccion' => 'Zona 2, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Contadora General',
                'area_trabajo' => 'Finanzas',
                'salario_base' => 7500.00,
                'fecha_ingreso' => '2019-03-10',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678902',
                'numero_irtra' => '1234568',
                'contacto_emergencia_nombre' => 'Elena Morales',
                'contacto_emergencia_telefono' => '11223344',
                'contacto_emergencia_relacion' => 'madre'
            ],
            [
                'codigo_empleado' => 'EMP003',
                'nombres' => 'Carlos Alberto',
                'apellidos' => 'Méndez Castillo',
                'dpi' => '1234567890103',
                'nit' => '12345680',
                'fecha_nacimiento' => '1988-11-08',
                'genero' => 'M',
                'estado_civil' => 'casado',
                'telefono' => '11223344',
                'email' => 'carlos.mendez@sansare.gob.gt',
                'direccion' => 'Zona 3, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Jefe de Obras Públicas',
                'area_trabajo' => 'Obras Públicas',
                'salario_base' => 9000.00,
                'fecha_ingreso' => '2018-06-01',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678903',
                'numero_irtra' => '1234569',
                'contacto_emergencia_nombre' => 'Ana Castillo',
                'contacto_emergencia_telefono' => '55667788',
                'contacto_emergencia_relacion' => 'esposa'
            ],
            [
                'codigo_empleado' => 'EMP004',
                'nombres' => 'Ana Lucía',
                'apellidos' => 'Hernández Vásquez',
                'dpi' => '1234567890104',
                'nit' => '12345681',
                'fecha_nacimiento' => '1992-02-14',
                'genero' => 'F',
                'estado_civil' => 'soltero',
                'telefono' => '55667788',
                'email' => 'ana.hernandez@sansare.gob.gt',
                'direccion' => 'Zona 4, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Secretaria Municipal',
                'area_trabajo' => 'Administración',
                'salario_base' => 5500.00,
                'fecha_ingreso' => '2021-02-15',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678904',
                'numero_irtra' => '1234570',
                'contacto_emergencia_nombre' => 'Luis Hernández',
                'contacto_emergencia_telefono' => '99887766',
                'contacto_emergencia_relacion' => 'padre'
            ],
            [
                'codigo_empleado' => 'EMP005',
                'nombres' => 'Roberto',
                'apellidos' => 'Pérez Gómez',
                'dpi' => '1234567890105',
                'nit' => '12345682',
                'fecha_nacimiento' => '1987-09-30',
                'genero' => 'M',
                'estado_civil' => 'casado',
                'telefono' => '99887766',
                'email' => 'roberto.perez@sansare.gob.gt',
                'direccion' => 'Zona 5, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Técnico en Sistemas',
                'area_trabajo' => 'Tecnología',
                'salario_base' => 6500.00,
                'fecha_ingreso' => '2020-08-20',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678905',
                'numero_irtra' => '1234571',
                'contacto_emergencia_nombre' => 'Carmen Gómez',
                'contacto_emergencia_telefono' => '33445566',
                'contacto_emergencia_relacion' => 'esposa'
            ],
            [
                'codigo_empleado' => 'EMP006',
                'nombres' => 'Sofía',
                'apellidos' => 'Morales Díaz',
                'dpi' => '1234567890106',
                'nit' => '12345683',
                'fecha_nacimiento' => '1995-05-18',
                'genero' => 'F',
                'estado_civil' => 'soltero',
                'telefono' => '33445566',
                'email' => 'sofia.morales@sansare.gob.gt',
                'direccion' => 'Zona 6, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Asistente Administrativa',
                'area_trabajo' => 'Administración',
                'salario_base' => 4500.00,
                'fecha_ingreso' => '2022-01-10',
                'tipo_contrato' => 'temporal',
                'estado' => 'activo',
                'numero_igss' => '12345678906',
                'numero_irtra' => '1234572',
                'contacto_emergencia_nombre' => 'Rosa Díaz',
                'contacto_emergencia_telefono' => '77889900',
                'contacto_emergencia_relacion' => 'madre'
            ],
            [
                'codigo_empleado' => 'EMP007',
                'nombres' => 'Luis Fernando',
                'apellidos' => 'Castillo Ruiz',
                'dpi' => '1234567890107',
                'nit' => '12345684',
                'fecha_nacimiento' => '1983-12-03',
                'genero' => 'M',
                'estado_civil' => 'casado',
                'telefono' => '77889900',
                'email' => 'luis.castillo@sansare.gob.gt',
                'direccion' => 'Zona 7, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Supervisor de Campo',
                'area_trabajo' => 'Obras Públicas',
                'salario_base' => 5800.00,
                'fecha_ingreso' => '2019-11-15',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678907',
                'numero_irtra' => '1234573',
                'contacto_emergencia_nombre' => 'Marta Ruiz',
                'contacto_emergencia_telefono' => '44556677',
                'contacto_emergencia_relacion' => 'esposa'
            ],
            [
                'codigo_empleado' => 'EMP008',
                'nombres' => 'Patricia',
                'apellidos' => 'López Martínez',
                'dpi' => '1234567890108',
                'nit' => '12345685',
                'fecha_nacimiento' => '1991-08-25',
                'genero' => 'F',
                'estado_civil' => 'casado',
                'telefono' => '44556677',
                'email' => 'patricia.lopez@sansare.gob.gt',
                'direccion' => 'Zona 8, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Enfermera Municipal',
                'area_trabajo' => 'Salud',
                'salario_base' => 6000.00,
                'fecha_ingreso' => '2020-04-01',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678908',
                'numero_irtra' => '1234574',
                'contacto_emergencia_nombre' => 'Carlos Martínez',
                'contacto_emergencia_telefono' => '66778899',
                'contacto_emergencia_relacion' => 'esposo'
            ],
            [
                'codigo_empleado' => 'EMP009',
                'nombres' => 'Miguel Ángel',
                'apellidos' => 'Ramírez Torres',
                'dpi' => '1234567890109',
                'nit' => '12345686',
                'fecha_nacimiento' => '1986-01-12',
                'genero' => 'M',
                'estado_civil' => 'soltero',
                'telefono' => '66778899',
                'email' => 'miguel.ramirez@sansare.gob.gt',
                'direccion' => 'Zona 9, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Conserje',
                'area_trabajo' => 'Servicios Generales',
                'salario_base' => 3500.00,
                'fecha_ingreso' => '2021-07-01',
                'tipo_contrato' => 'indefinido',
                'estado' => 'activo',
                'numero_igss' => '12345678909',
                'numero_irtra' => '1234575',
                'contacto_emergencia_nombre' => 'Ana Torres',
                'contacto_emergencia_telefono' => '22334455',
                'contacto_emergencia_relacion' => 'madre'
            ],
            [
                'codigo_empleado' => 'EMP010',
                'nombres' => 'Carmen Rosa',
                'apellidos' => 'Flores Aguilar',
                'dpi' => '1234567890110',
                'nit' => '12345687',
                'fecha_nacimiento' => '1989-04-07',
                'genero' => 'F',
                'estado_civil' => 'casado',
                'telefono' => '22334455',
                'email' => 'carmen.flores@sansare.gob.gt',
                'direccion' => 'Zona 10, Sansare, El Progreso',
                'departamento' => 'El Progreso',
                'municipio' => 'Sansare',
                'puesto' => 'Auxiliar de Contabilidad',
                'area_trabajo' => 'Finanzas',
                'salario_base' => 4800.00,
                'fecha_ingreso' => '2021-09-15',
                'tipo_contrato' => 'temporal',
                'estado' => 'activo',
                'numero_igss' => '12345678910',
                'numero_irtra' => '1234576',
                'contacto_emergencia_nombre' => 'Pedro Aguilar',
                'contacto_emergencia_telefono' => '88990011',
                'contacto_emergencia_relacion' => 'esposo'
            ]
        ];
        
        foreach ($empleados as $empleado) {
            Empleado::create($empleado);
        }
    }
}
